import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root' // Der Service wird in der gesamten App verfügbar gemacht
})
//export class TranslationService {

 // constructor() { }
//}

export class TranslationService {
  private translations: { [key: string]: { [key: string]: string } } = {
    en: {
      ABOUT_ME: 'About me',
      SKILLS: 'Skills',
      PORTFOLIO: 'Portfolio',
      CONTACT: 'Contact',
      HOME: 'Home',

      IMPRINT_TITLE: 'Imprint',
      IMPRINT_INFO: 'Information according to § 5 DDG',    
      PHONE: 'Phone',
      EMAIL: 'Email',
      DISCLAIMER_TITLE: 'Disclaimer',
      LIABILITY_CONTENT: 'Liability for Content',
      LIABILITY_LINKS: 'Liability for Links',
      COPYRIGHT: 'Copyright',
      DATA_PROTECTION: 'Data Protection',
      GOOGLE_ANALYTICS: 'Google Analytics',
      GOOGLE_ADSENSE: 'Google AdSense',
      GENERATED_BY: 'Imprint generated by',
      DISCLAIMER_TEXT: 'The contents of our pages were created with the utmost care. However, we cannot guarantee the accuracy, completeness, or timeliness of the contents. As a service provider, we are responsible for our own content on these pages under general laws according to § 7 para.1 DDG. However, according to §§ 8 to 10 DDG, we are not obligated as a service provider to monitor transmitted or stored third-party information or to investigate circumstances that indicate illegal activity. Obligations to remove or block the use of information under general laws remain unaffected. However, liability in this regard is only possible from the time of knowledge of a concrete infringement. Upon becoming aware of corresponding infringements, we will remove these contents immediately.',
      LIABILITY_LINKS_TEXT:'Our offer contains links to external third-party websites over whose content we have no control. Therefore, we cannot assume any liability for this external content. The respective provider or operator of the pages is always responsible for the contents of the linked pages. The linked pages were checked for possible legal violations at the time of linking. Illegal content was not recognizable at the time of linking. However, permanent monitoring of the content of the linked pages is not reasonable without specific indications of a legal violation. Upon becoming aware of legal violations, we will remove such links immediately.',      
      COPYRIGHT_TEXT:'The content and works created by the site operators on these pages are subject to German copyright law. The duplication, processing, distribution, and any form of use outside the limits of copyright require the written consent of the respective author or creator. Downloads and copies of this site are only permitted for private, non-commercial use. Insofar as the content on this site was not created by the operator, the copyrights of third parties are respected. In particular, third-party content is marked as such. Should you nevertheless become aware of a copyright infringement, please inform us accordingly. Upon becoming aware of legal violations, we will remove such content immediately.',
      DATA_PROTECTION_TEXT:'The use of our website is generally possible without providing personal data. Insofar as personal data (e.g., name, address, or email addresses) is collected on our pages, this is always done on a voluntary basis, as far as possible. This data will not be passed on to third parties without your express consent. We point out that data transmission on the Internet (e.g., communication by email) can have security vulnerabilities. A complete protection of data against access by third parties is not possible. The use of contact data published within the scope of the imprint obligation by third parties for sending unsolicited advertising and information materials is hereby expressly prohibited. The operators of the pages expressly reserve the right to take legal steps in the event of unsolicited sending of advertising information, such as spam emails.',
      GOOGLE_ANALYTICS_TEXT: 'This website uses Google Analytics, a web analysis service of Google Inc. ("Google"). Google Analytics uses "cookies," text files that are stored on your computer and allow an analysis of your use of the website. The information generated by the cookie about your use of this website (including your IP address) is transmitted to a Google server in the USA and stored there. Google will use this information to evaluate your use of the website, compile reports on website activity for website operators, and provide other services related to website and Internet usage. Google may also transfer this information to third parties if required by law or if third parties process this data on behalf of Google. Google will not associate your IP address with any other data held by Google. You can prevent the installation of cookies by setting your browser software accordingly; however, please note that in this case, you may not be able to fully use all functions of this website. By using this website, you consent to the processing of the data collected about you by Google in the manner and for the purposes set out above.',
      GOOGLE_ADSENSE_TEXT: 'This website uses Google AdSense, a web advertising service of Google Inc., USA ("Google"). Google AdSense uses "cookies" (text files) that are stored on your computer and allow an analysis of your use of the website. Google AdSense also uses "web beacons" (small invisible graphics) to collect information. Through the use of web beacons, simple actions such as visitor traffic on the website can be recorded and collected. The information generated by the cookie and/or web beacon about your use of this website (including your IP address) is transmitted to a Google server in the USA and stored there. Google will use this information to evaluate your use of the website regarding ads, compile reports on website activity and ads for website operators, and provide further services related to website and Internet usage. Google may also transfer this information to third parties if required by law or if third parties process this data on behalf of Google. Google will not associate your IP address with any other data held by Google. You can prevent the storage of cookies on your hard drive and the display of web beacons by selecting "do not accept cookies" in your browser settings (in Internet Explorer under "Tools > Internet Options > Privacy > Settings"; in Firefox under "Tools > Options > Privacy > Cookies"); however, please note that in this case, you may not be able to fully use all functions of this website. By using this website, you consent to the processing of data collected about you by Google in the manner and for the purposes described above.',
      
      PRIVACY_TITLE:'Privacy Policy',
      DATA_PROTECTION_OVERVIEW:'1. Data Protection Overview',
      GENERAL_INFORMATION:'General Information',
      GENERAL_INFO_CONTENT:'The following information provides a simple overview of what happens to your personal data when you visit this website. Personal data refers to all data that can personally identify you. For detailed information on data protection, please refer to our privacy policy outlined below.',
      DATA_COLLECTION:'Data Collection on This Website',
      RESPONSIBLE_PARTY:'ho is responsible for data collection on this website?',
      RESPONSIBLE_PARTY_CONTENT:'Data processing on this website is carried out by the website operator. Their contact details can be found in the section "Notice concerning the responsible party" in this privacy policy.',
      DATA_COLLECT:'How do we collect your data?',
      DATA_COLLECT_CONTENT:'Some of your data is collected when you provide it to us. This could, for example, be data you enter in a contact form.',
      DATA_COLLECT_CONTENT_AUTO:'Other data is collected automatically or with your consent when you visit the website. This primarily includes technical data (e.g., internet browser, operating system, or time of page access). The collection of this data occurs automatically as soon as you enter this website.',
      DATA_USE:'What do we use your data for?',
      DATA_USE_CONTENT:'Part of the data is collected to ensure the website is provided error-free. Other data may be used to analyze your user behavior.',
      DATA_RIGHTS:'What rights do you have regarding your data?',
      DATA_RIGHTS_CONTENT:'You have the right to receive information about the origin, recipient, and purpose of your stored personal data free of charge at any time. You also have the right to request the correction or deletion of this data. If you have given consent for data processing, you can revoke this consent at any time for the future. Additionally, you have the right to request the restriction of processing of your personal data under certain circumstances. Furthermore, you have the right to lodge a complaint with the competent supervisory authority.',
      DATA_RIGHTS_CONTACT:'You can contact us at any time for questions related to data protection.',
      
      HOSTING_TITLE:'We host the content of our website with the following provider:',
      PROVIDER_TITLE:'The provider is ALL-INKL.COM - Neue Medien Münnich, Owner René Münnich, Hauptstraße 68, 02742 Friedersdorf (hereinafter referred to as All-Inkl). For more details, refer to All-Inkl s privacy policy:',
      PROVIDER_USE:'The use of All-Inkl is based on Art. 6(1)(f) GDPR. We have a legitimate interest in the most reliable possible presentation of our website. If consent has been requested, processing is based solely on Art. 6(1)(a) GDPR and § 25(1) TTDSG, insofar as consent includes the storage of cookies or access to information on the users device (e.g., device fingerprinting) as defined by TTDSG. Consent can be revoked at any time.',
      ORDER_PROCESSING:'Order Processing',
      PROCESSING_AGREEMENT:'We have concluded a data processing agreement (DPA) with the above-mentioned provider. This is a contract required under data protection law, which ensures that they only process personal data of our website visitors according to our instructions and in compliance with the GDPR.',

      MANDATORY_INFORMATION:'3. General Information and Mandatory Disclosures',
      MANDATORY_INFO_CONTENT:'The operators of this site take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with statutory data protection regulations and this privacy policy.',
      MANDATORY_INFO_CONTENT_1:'When you use this website, various personal data is collected. Personal data is data with which you can be personally identified. This privacy policy explains what data we collect and what we use it for. It also explains how and for what purpose this is done.',
      MANDATORY_INFO_CONTENT_2:'Please note that data transmission on the Internet (e.g., communication by email) may have security vulnerabilities. Complete protection of data from third-party access is not possible.',

      NOTICE_RESPONSIBLE_PARTY:'Notice Concerning the Responsible Party',
      NOTICE_RESPONSIBLE_PARTY_2:'The responsible party for data processing on this website is:',
      NOTICE_RESPONSIBLE_CONTENT:'The responsible party is the natural or legal person who alone or jointly with others determines the purposes and means of processing personal data (e.g., names, email addresses, etc.).',
      STORAGE_DURATION:'Storage Duration',
      STORAGE_DURATION_CONTENT:'Unless a more specific storage period has been mentioned within this privacy policy, your personal data will remain with us until the purpose for the data processing no longer applies. If you assert a legitimate request for deletion or revoke your consent to data processing, your data will be deleted unless we have other legally permissible reasons for storing your personal data (e.g., tax or commercial law retention periods); in the latter case, deletion will occur after these reasons cease to apply.',
      LEGAL_BASES:'General Information on Legal Bases for Data Processing',
      LEGAL_BASES_CONTENT:'If you have consented to data processing, we process your personal data based on Art. 6(1)(a) GDPR or Art. 9(2)(a) GDPR if special data categories according to Art. 9(1) GDPR are processed. In the case of explicit consent for the transfer of personal data to third countries, data processing is also based on Art. 49(1)(a) GDPR. If you have consented to the storage of cookies or access to information on your end device (e.g., via device fingerprinting), data processing is additionally based on § 25(1) TTDSG. Consent can be revoked at any time. If your data is required for contract performance or pre-contractual measures, we process your data based on Art. 6(1)(b) GDPR. Furthermore, we process your data if it is necessary for the fulfillment of a legal obligation based on Art. 6(1)(c) GDPR. Data processing may also be based on our legitimate interest according to Art. 6(1)(f) GDPR. Information on the relevant legal basis for processing in each case is provided in the following sections of this privacy policy.',
      PERSONAL_DATA_TITLE:'Recipients of Personal Data',
      PERSONAL_DATA_CONTENT:'As part of our business activities, we work with various external parties. In some cases, it is also necessary to transmit personal data to these external parties. We only share personal data with external parties if this is necessary for contract fulfillment, if we are legally obligated to do so (e.g., sharing data with tax authorities), if we have a legitimate interest in sharing data according to Art. 6(1)(f) GDPR, or if another legal basis permits data sharing. When using processors, we only share personal data based on a valid data processing agreement. In the case of joint processing, a joint processing agreement is concluded.',
      REVOCATION_DATA:'Revocation of Your Consent to Data Processing',
      REVOCATION_DATA_CONTENT:'Many data processing operations are only possible with your explicit consent. You can revoke consent you have already given at any time. The legality of data processing carried out until the revocation remains unaffected by the revocation.',
      RIGHT_TO_OBJECT_TITLE:'Right to Object to Data Collection in Specific Cases and to Direct Advertising (Art. 21 GDPR)',
      RIGHT_TO_OBJECT_CONTENT_1:'IF DATA PROCESSING IS BASED ON ART. 6(1)(E) OR (F) GDPR, YOU HAVE THE RIGHT TO OBJECT TO THE PROCESSING OF YOUR PERSONAL DATA AT ANY TIME FOR REASONS ARISING FROM YOUR PARTICULAR SITUATION; THIS ALSO APPLIES TO PROFILING BASED ON THESE PROVISIONS. THE RELEVANT LEGAL BASIS ON WHICH PROCESSING IS BASED CAN BE FOUND IN THIS PRIVACY POLICY. IF YOU OBJECT, WE WILL NO LONGER PROCESS YOUR PERSONAL DATA UNLESS WE CAN DEMONSTRATE COMPELLING LEGITIMATE GROUNDS FOR THE PROCESSING THAT OVERRIDE YOUR INTERESTS, RIGHTS, AND FREEDOMS, OR IF THE PROCESSING IS FOR THE ESTABLISHMENT, EXERCISE, OR DEFENSE OF LEGAL CLAIMS (OBJECTION PURSUANT TO ART. 21(1) GDPR).',
      RIGHT_TO_OBJECT_CONTENT_2:'IF YOUR PERSONAL DATA IS PROCESSED FOR DIRECT ADVERTISING PURPOSES, YOU HAVE THE RIGHT TO OBJECT AT ANY TIME TO THE PROCESSING OF YOUR PERSONAL DATA FOR SUCH ADVERTISING; THIS ALSO APPLIES TO PROFILING INSOFAR AS IT IS ASSOCIATED WITH SUCH DIRECT ADVERTISING. IF YOU OBJECT, YOUR PERSONAL DATA WILL NO LONGER BE USED FOR DIRECT ADVERTISING PURPOSES (OBJECTION PURSUANT TO ART. 21(2) GDPR).',
      RIGHT_TO_LODGE_TITLE:'Right to Lodge a Complaint with the Competent Supervisory Authority',
      RIGHT_TO_LODGE_CONTENT:'In the event of violations of the GDPR, data subjects have the right to lodge a complaint with a supervisory authority, particularly in the member state of their habitual residence, their place of work, or the location of the alleged violation. The right to lodge a complaint is without prejudice to other administrative or judicial remedies.',
      PORTABILITY_TITLE:'Right to Data Portability',
      PORTABILITY_CONTENT:'You have the right to have data that we process based on your consent or in fulfillment of a contract handed over to you or a third party in a commonly used, machine-readable format. If you request the direct transfer of the data to another controller, this will only be done to the extent technically feasible.',
      DELETION_TITLE:'Access, Correction, and Deletion',
      DELETION_CONTENT:'Within the framework of applicable legal provisions, you have the right at any time to access information free of charge about your stored personal data, its origin, and recipients, and the purpose of data processing, and, if applicable, a right to correction or deletion of this data. You can contact us at any time for this purpose as well as for further questions on the topic of personal data.',
      RIGHT_PROCESSING_TITLE:'Right to Restrict Processing',
      RIGHT_PROCESSING_CONTENT:'You have the right to request the restriction of the processing of your personal data. To do this, you can contact us at any time. The right to restrict processing exists in the following cases:',
      LIST_CONTENT_1:'If you dispute the accuracy of your personal data stored with us, we usually need time to verify this. For the duration of the verification, you have the right to request the restriction of the processing of your personal data.',
      LIST_CONTENT_2:'If the processing of your personal data was/is unlawful, you can request the restriction of data processing instead of deletion.',
      LIST_CONTENT_3:'If we no longer need your personal data, but you need it to exercise, defend, or assert legal claims, you have the right to request the restriction of the processing of your personal data instead of deletion.',
      LIST_CONTENT_4:'If you have filed an objection under Art. 21(1) GDPR, a balance must be struck between your interests and ours. As long as it has not yet been determined whose interests prevail, you have the right to request the restriction of the processing of your personal data.',
      RIGHT_PROCESSING_CONTENT_2:'If you have restricted the processing of your personal data, such data may – apart from being stored – only be processed with your consent or for the establishment, exercise, or defense of legal claims or for protecting the rights of another natural or legal person or for reasons of important public interest of the European Union or a member state.',
      SSL_TITLE:'SSL or TLS Encryption',
      SSL_CONTENT:'This site uses SSL or TLS encryption for security reasons and to protect the transmission of confidential content, such as orders or inquiries that you send to us as the site operator. You can recognize an encrypted connection by the address line of the browser switching from "http://" to "https://" and the lock icon in your browser line.',
      SSL_CONTENT_2:'If SSL or TLS encryption is activated, the data you transmit to us cannot be read by third parties.',
      COLLECTION_WEBSITE:'4. Data Collection on This Website',
      COLLECTION_WEBSITE_TITLE:'Request by Email, Phone, or Fax',
      COLLECTION_WEBSITE_CONTENT_1:'If you contact us by email, phone, or fax, your inquiry, including all personal data resulting from it (name, inquiry), will be stored and processed by us for the purpose of handling your request. We do not pass these data on without your consent.',
      COLLECTION_WEBSITE_CONTENT_2:'The processing of these data is based on Art. 6(1)(b) GDPR if your inquiry is related to the fulfillment of a contract or is necessary for the implementation of pre-contractual measures. In all other cases, processing is based on our legitimate interest in the effective handling of inquiries addressed to us (Art. 6(1)(f) GDPR) or on your consent (Art. 6(1)(a) GDPR) if this has been requested; consent can be revoked at any time.',
      COLLECTION_WEBSITE_CONTENT_3:'The data sent to us via contact requests will remain with us until you request us to delete it, revoke your consent to its storage, or the purpose for the data storage no longer applies (e.g., after your request has been processed). Mandatory legal provisions – particularly legal retention periods – remain unaffected.',
      COLLECTION_WEBSITE_CONTENT_4:'Source:',

      HEADER_TITLE: 'I am',
      HEADER_SUBTITLE: 'FRONTEND DEVELOPER',
      HEADER_BUTTON: 'Lets talk!',

      SCROLL_ICON:'Scroll down',

      ABOUT_ME_TITLE:'About me',
      ABOUT_ME_DESCRIPTION:'Im a front-end developer with extensive experience in Angular. With a solid background in engineering and technical fields, I bring a versatile profile uniting technological expertise and creative IT skills. My studies provide a profound understanding of innovative technologies, laying a robust foundation for my role as a web developer. Proficient in JavaScript, I am a skilled web developer with a strong foundation in IT practices. My expertise includes advanced version control using Git, seamless integration of APIs, and dedicated adherence to SCRUM methodology for efficient project management. I possess an in-depth understanding of HTML and prioritize secure coding practices to ensure robust web solutions. Additionally, I leverage frameworks like Angular, incorporating libraries such as Bootstrap and employing cascading style sheets (CSS) for creating visually appealing and responsive web designs.',
      ABOUT_ME_DESCRIPTION_2:'My proficiency extends to app development, demonstrating a comprehensive understanding of modern web technologies and a commitment to delivering innovative and user-centric solutions. My expertise extends to app development, showcasing a well-rounded understanding of modern web technologies.     ',
      ABOUT_ME_DESCRIPTION_3:'With a solid background in engineering sciences and technical fields, I present a versatile profile that bridges technological expertise and creative IT skills. My studies have provided me with a comprehensive understanding of innovative technologies and communication platforms, forming a solid foundation for my role as a web developer.',

      MY_SKILLS_TITLE:'My Skills',
      MY_SKILLS_DESCRIPTION:'I have honed my frontend development skills, enabling me to successfully craft various tangible projects.',
      MY_SKILLS_BUTTON:'Get in touch',
      
      MY_WORKS_TITLE:'',
      MY_WORKS_DESCRIPTION:'This page is a sample of my work - please feel free to try them out.',

      JOIN_DESCRIPTION:'Ive crafted a practical task management solution inspired by the Kanban System, which offers an effortless way to arrange tasks intuitively using a simple drag-and-drop mechanism. Users can seamlessly assign tasks to specific team members, while also benefiting from the ability to categorize tasks for optimal organization. My programming expertise shines through in the seamless integration of these features, resulting in a user-friendly yet robust task management tool.',
      KOCHWELT_DESCRIPTION:'A Pokédex is an interactive web application that uses APIs to fetch data about Pokémon species. Built with JavaScript, it retrieves and displays information such as appearance, abilities, and habitats dynamically, allowing users to explore various Pokémon easily.',
      EPL_DESCRIPTION:'Developed using an object-oriented approach, the "Jump, Run, and Throw" game follows a meticulously crafted design. In this captivating gaming experience, players assist Pepe in his quest to collect coins while strategically acquiring tabasco salsa to counter the antics of the frenzied hen. The implementation highlights my adept programming skills, as I seamlessly integrate interactive elements, character behaviors, and power-up dynamics, resulting in an immersive and engaging gameplay environment.',

      CONTACT_TITLE:'Contact',
      CONTACT_DESCRIPTION:'Got a problem to solve?',
      CONTACT_DESCRIPTION_2:'Contact me through this form, I am interested in hearing you, knowing your ideas and contributing to your projects with my work.',
      CONTACT_DESCRIPTION_3:'Need a Frontend developer? ',
      CONTACT_DESCRIPTION_4:'Contact me!',

      //Form
      NAME_INPUT:'Your name',
      EMAIL_INPUT:'Your email',
      MASSAGE_INPUT:'Your message',
      NAME_REQUIRED:'Your name is required',
      EMAIL_REQUIRED:'Your email is required',
      MASSAGE_REQUIRED:'Your message is required',
      PRIVACY_CHECK:'I have read the',
      PRIVACY_CHECK_2:'Privacy Policy',
      PRIVACY_CHECK_3:'and agree to the processing of my data as described.',
      BUTTON_SENDMAIL:'Send Message',
      SENDMAIL_CONTENT:'Your email has been send successfully!',

      FOOTER_IMPRINT:'Imprint',

    },
    de: {
      ABOUT_ME: 'Über mich',
      SKILLS: 'Fähigkeiten',
      PORTFOLIO: 'Portfolio',
      CONTACT: 'Kontakt',
      HOME: 'Startseite',

      IMPRINT_TITLE: 'Impressum',
      IMPRINT_INFO: 'Angaben gemäß § 5 DDG',    
      PHONE: 'Telefon',
      EMAIL: 'E-Mail',
      DISCLAIMER_TITLE: 'Haftungsausschluss',
      LIABILITY_CONTENT: 'Haftung für Inhalte',
      LIABILITY_LINKS: 'Haftung für Links',
      COPYRIGHT: 'Urheberrecht',
      DATA_PROTECTION: 'Datenschutz',
      GOOGLE_ANALYTICS: 'Google Analytics',
      GOOGLE_ADSENSE: 'Google AdSense',
      GENERATED_BY: 'Impressum erstellt von',
      DISCLAIMER_TEXT: 'Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 DDG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 DDG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.',
      LIABILITY_LINKS_TEXT:'Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.',      
      COPYRIGHT_TEXT:'Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.',
      DATA_PROTECTION_TEXT:'Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. <br>Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich. Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.',
      GOOGLE_ANALYTICS_TEXT: 'Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. ("Google"). Google Analytics verwendet sog. "cookies," Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglicht. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website (einschließlich Ihrer IP-Adresse) wird an einen Server von Google in den USA übertragen und dort gespeichert. Google wird diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google in Verbindung bringen. Sie können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.',
      GOOGLE_ADSENSE_TEXT: 'Diese Website benutzt Google Adsense, einen Webanzeigendienst der Google Inc., USA ("Google"). Google Adsense verwendet sog. "Cookies" (Textdateien), die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglicht. Google Adsense verwendet auch sog. "Web Beacons" (kleine unsichtbare Grafiken) zur Sammlung von Informationen. Durch die Verwendung des Web Beacons können einfache Aktionen wie der Besucherverkehr auf der Webseite aufgezeichnet und gesammelt werden. Die durch den Cookie und/oder Web Beacon erzeugten Informationen über Ihre Benutzung dieser Website (einschließlich Ihrer IP-Adresse) werden an einen Server von Google in den USA übertragen und dort gespeichert. Google wird diese Informationen benutzen, um Ihre Nutzung der Website im Hinblick auf die Anzeigen auszuwerten, um Reports über die Websiteaktivitäten und Anzeigen für die Websitebetreiber zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google in Verbindung bringen. Das Speichern von Cookies auf Ihrer Festplatte und die Anzeige von Web Beacons können Sie verhindern, indem Sie in Ihren Browser-Einstellungen "keine Cookies akzeptieren" wählen (Im MS Internet-Explorer unter "Extras > Internetoptionen > Datenschutz > Einstellung"; im Firefox unter "Extras > Einstellungen > Datenschutz > Cookies"); wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.',
      
      PRIVACY_TITLE:'Datenschutzerklärung',
      DATA_PROTECTION_OVERVIEW:'1. Datenschutz auf einen Blick',
      GENERAL_INFORMATION:'Allgemeine Hinweise',
      GENERAL_INFO_CONTENT:'Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie persönlich identifiziert werden können. Ausführliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgeführten Datenschutzerklärung.',
      DATA_COLLECTION:'Datenerfassung auf dieser Website',
      RESPONSIBLE_PARTY:'Wer ist verantwortlich für die Datenerfassung auf dieser Website?',
      RESPONSIBLE_PARTY_CONTENT:'Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten können Sie dem Abschnitt „Hinweis zur Verantwortlichen Stelle“ in dieser Datenschutzerklärung entnehmen.',
      DATA_COLLECT:'Wie erfassen wir Ihre Daten?',
      DATA_COLLECT_CONTENT:'Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z.B. um Daten handeln, die Sie in ein Kontaktformular eingeben.',
      DATA_COLLECT_CONTENT_AUTO:'Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Das sind vor allem technische Daten (z.B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie diese Website betreten.',
      DATA_USE:'Wofür nutzen wir Ihre Daten?',
      DATA_USE_CONTENT:'Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können zur Analyse Ihres Nutzerverhaltens verwendet werden.',
      DATA_RIGHTS:'Welche Rechte haben Sie bezüglich Ihrer Daten?',
      DATA_RIGHTS_CONTENT:'Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben außerdem ein Recht, die Berichtigung oder Löschung dieser Daten zu verlangen. Wenn Sie eine Einwilligung zur Datenverarbeitung erteilt haben, können Sie diese Einwilligung jederzeit für die Zukunft widerrufen. Au&ßerdem haben Sie das Recht, unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Des Weiteren steht Ihnen ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu.',
      DATA_RIGHTS_CONTACT:'Hierzu sowie zu weiteren Fragen zum Thema Datenschutz können Sie sich jederzeit an uns wenden.',

      HOSTING_TITLE:'Wir hosten die Inhalte unserer Website bei folgendem Anbieter:',
      PROVIDER_TITLE:'Anbieter ist die ALL-INKL.COM - Neue Medien Münnich, Inh. René Münnich, Hauptstraße 68, 02742 Friedersdorf (nachfolgend All-Inkl). Details entnehmen Sie der Datenschutzerklärung von All-Inkl:',
      PROVIDER_USE:'Die Verwendung von All-Inkl erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Wir haben ein berechtigtes Interesse an einer möglichst zuverlässigen Darstellung unserer Website. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TTDSG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endgerät des Nutzers (z.B. Device-Fingerprinting) im Sinne des TTDSG umfasst. Die Einwilligung ist jederzeit widerrufbar.',
      ORDER_PROCESSING:'Auftragsverarbeitung',
      PROCESSING_AGREEMENT:'Wir haben einen Vertrag über Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gewährleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.',

      MANDATORY_INFORMATION:'3. Allgemeine Hinweise und Pflichtinformationen',
      MANDATORY_INFO_CONTENT:'Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung.',
      MANDATORY_INFO_CONTENT_1:'Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie persönlich identifiziert werden können. Die vorliegende Datenschutzerklärung erläutert, welche Daten wir erheben und wofür wir sie nutzen. Sie erläutert auch, wie und zu welchem Zweck das geschieht.',
      MANDATORY_INFO_CONTENT_2:'Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.',

      NOTICE_RESPONSIBLE_PARTY:'Hinweis zur verantwortlichen Stelle',
      NOTICE_RESPONSIBLE_PARTY_2:'Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:',
      NOTICE_RESPONSIBLE_CONTENT:'Verantwortliche Stelle ist die natürliche oder juristische Person, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z.B. Namen, E-Mail-Adressen o.Ä.) entscheidet.',
      STORAGE_DURATION:'Speicherdauer',
      STORAGE_DURATION_CONTENT:'Soweit innerhalb dieser Datenschutzerklärung keine speziellere Speicherdauer genannt wurde, verbleiben Ihre personenbezogenen Daten bei uns, bis der Zweck für die Datenverarbeitung entfüllt. Wenn Sie ein berechtigtes Löschersuchen geltend machen oder eine Einwilligung zur Datenverarbeitung widerrufen, werden Ihre Daten gelöscht, sofern wir keine anderen rechtlich zulässigen Gründe für die Speicherung Ihrer personenbezogenen Daten haben (z.B. steuer- oder handelsrechtliche Aufbewahrungsfristen); im letztgenannten Fall erfolgt die Löschung nach Fortfall dieser Gründe.',
      LEGAL_BASES:'Allgemeine Hinweise zu den Rechtsgrundlagen der Datenverarbeitung auf dieser Website',
      LEGAL_BASES_CONTENT:'Sofern Sie in die Datenverarbeitung eingewilligt haben, verarbeiten wir Ihre personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO bzw. Art. 9 Abs. 2 lit. a DSGVO, sofern besondere Datenkategorien nach Art. 9 Abs. 1 DSGVO verarbeitet werden. Im Falle einer ausdrücklichen Einwilligung in die übertragung personenbezogener Daten in Drittstaaten erfolgt die Datenverarbeitung außerdem auf Grundlage von Art. 49 Abs. 1 lit. a DSGVO. Sofern Sie in die Speicherung von Cookies oder in den Zugriff auf Informationen in Ihr Endgerät (z.B. via Device-Fingerprinting) eingewilligt haben, erfolgt die Datenverarbeitung zusätzlich auf Grundlage von § 25 Abs. 1 TTDSG. Die Einwilligung ist jederzeit widerrufbar. Sind Ihre Daten zur Vertragserfüllung oder zur Durchführung vorvertraglicher Maßnahmen erforderlich, verarbeiten wir Ihre Daten auf Grundlage des Art. 6 Abs. 1 lit. b DSGVO. Des Weiteren verarbeiten wir Ihre Daten, sofern diese zur Erfüllung einer rechtlichen Verpflichtung erforderlich sind auf Grundlage von Art. 6 Abs. 1 lit. c DSGVO. Die Datenverarbeitung kann ferner auf Grundlage unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO erfolgen. über die jeweils im Einzelfall einschlägigen Rechtsgrundlagen wird in den folgenden Absätzen dieser Datenschutzerklärung informiert.',
      PERSONAL_DATA_TITLE:'Empfänger von personenbezogenen Daten',
      PERSONAL_DATA_CONTENT:'Im Rahmen unserer Geschäftstätigkeit arbeiten wir mit verschiedenen externen Stellen zusammen. Dabei ist teilweise auch eine übermittlung von personenbezogenen Daten an diese externen Stellen erforderlich. Wir geben personenbezogene Daten nur dann an externe Stellen weiter, wenn dies im Rahmen einer Vertragserfüllung erforderlich ist, wenn wir gesetzlich hierzu verpflichtet sind (z.B. Weitergabe von Daten an Steuerbehörden), wenn wir ein berechtigtes Interesse nach Art. 6 Abs. 1 lit. f DSGVO an der Weitergabe haben oder wenn eine sonstige Rechtsgrundlage die Datenweitergabe erlaubt. Beim Einsatz von Auftragsverarbeitern geben wir personenbezogene Daten unserer Kunden nur auf Grundlage eines gültigen Vertrags über Auftragsverarbeitung weiter. Im Falle einer gemeinsamen Verarbeitung wird ein Vertrag über gemeinsame Verarbeitung geschlossen.',
      REVOCATION_DATA:'Widerruf Ihrer Einwilligung zur Datenverarbeitung',
      REVOCATION_DATA_CONTENT:'Viele Datenverarbeitungsvorgänge sind nur mit Ihrer ausdrücklichen Einwilligung möglich. Sie können eine bereits erteilte Einwilligung jederzeit widerrufen. Die Rechtmöigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unberührt.',
      RIGHT_TO_OBJECT_TITLE:'Widerspruchsrecht gegen die Datenerhebung in besonderen Fällen sowie gegen Direktwerbung (Art. 21 DSGVO)',
      RIGHT_TO_OBJECT_CONTENT_1:'WENN DIE DATENVERARBEITUNG AUF GRUNDLAGE VON ART. 6 ABS. 1 LIT. E ODER F DSGVO ERFOLGT, HABEN SIE JEDERZEIT DAS RECHT, AUS GRÜNDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE VERARBEITUNG IHRER PERSONENBEZOGENEN DATEN WIDERSPRUCH EINZULEGEN; DIES GILT AUCH FÜR EIN AUF DIESE BESTIMMUNGEN GESTÜTZTES PROFILING. DIE JEWEILIGE RECHTSGRUNDLAGE, AUF DENEN EINE VERARBEITUNG BERUHT, ENTNEHMEN SIE DIESER DATENSCHUTZERKLÄRUNG. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN WIR IHRE BETROFFENEN PERSONENBEZOGENEN DATEN NICHT MEHR VERARBEITEN, ES SEI DENN, WIR KÖNNEN ZWINGENDE SCHUTZWÜRDIGE GRÜNDE FÜR DIE VERARBEITUNG NACHWEISEN, DIE IHRE INTERESSEN, RECHTE UND FREIHEITEN ÜBERWIEGEN ODER DIE VERARBEITUNG DIENT DER GELTENDMACHUNG, AUSÜBUNG ODER VERTEIDIGUNG VON RECHTSANSPRÜCHEN (WIDERSPRUCH NACH ART. 21 ABS. 1 DSGVO).',
      RIGHT_TO_OBJECT_CONTENT_2:'WERDEN IHRE PERSONENBEZOGENEN DATEN VERARBEITET, UM DIREKTWERBUNG ZU BETREIBEN, SO HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE DERARTIGER WERBUNG EINZULEGEN; DIES GILT AUCH FÜR DAS PROFILING, SOWEIT ES MIT SOLCHER DIREKTWERBUNG IN VERBINDUNG STEHT. WENN SIE WIDERSPRECHEN, WERDEN IHRE PERSONENBEZOGENEN DATEN ANSCHLIESSEND NICHT MEHR ZUM ZWECKE DER DIREKTWERBUNG VERWENDET (WIDERSPRUCH NACH ART. 21 ABS. 2 DSGVO).',
      RIGHT_TO_LODGE_TITLE:'Beschwerderecht bei der zuständigen Aufsichtsbehörde',
      RIGHT_TO_LODGE_CONTENT:'Im Falle von Verstößen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat ihres gewöhnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes zu. Das Beschwerderecht besteht unbeschadet anderweitiger verwaltungsrechtlicher oder gerichtlicher Rechtsbehelfe.',
      PORTABILITY_TITLE:'Recht auf Datenübertragbarkeit',
      PORTABILITY_CONTENT:'Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem gängigen, maschinenlesbaren Format aushändigen zu lassen. Sofern Sie die direkte Übertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.',
      DELETION_TITLE:'Auskunft, Berichtigung und Löschung',
      DELETION_CONTENT:'Sie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empfänger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung oder Löschung dieser Daten. Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten können Sie sich jederzeit an uns wenden.',
      RIGHT_PROCESSING_TITLE:'Recht auf Einschränkung der Verarbeitung',
      RIGHT_PROCESSING_CONTENT:'Sie haben das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Hierzu können Sie sich jederzeit an uns wenden. Das Recht auf Einschränkung der Verarbeitung besteht in folgenden Fällen:',
      LIST_CONTENT_1:'Wenn Sie die Richtigkeit Ihrer bei uns gespeicherten personenbezogenen Daten bestreiten, benötigen wir in der Regel Zeit, um dies zu überprüfen. Für die Dauer der Prüfung haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.',
      LIST_CONTENT_2:'Wenn die Verarbeitung Ihrer personenbezogenen Daten unrechtmäßig geschah/geschieht, können Sie statt der Löschung die Einschränkung der Datenverarbeitung verlangen.',
      LIST_CONTENT_3:'Wenn wir Ihre personenbezogenen Daten nicht mehr benötigen, Sie sie jedoch zur Ausübung, Verteidigung oder Geltendmachung von Rechtsansprüchen benötigen, haben Sie das Recht, statt der Löschung die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.',
      LIST_CONTENT_4:'Wenn Sie einen Widerspruch nach Art. 21 Abs. 1 DSGVO eingelegt haben, muss eine Abwägung zwischen Ihren und unseren Interessen vorgenommen werden. Solange noch nicht feststeht, wessen Interessen überwiegen, haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.',
      RIGHT_PROCESSING_CONTENT_2:'Wenn Sie die Verarbeitung Ihrer personenbezogenen Daten eingeschränkt haben, dürfen diese Daten, von ihrer Speicherung abgesehen, nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder aus Gründen eines wichtigen öffentlichen Interesses der Europäischen Union oder eines Mitgliedstaats verarbeitet werden.',
      SSL_TITLE:'SSL- bzw. TLS-Verschlüsselung',
      SSL_CONTENT:'Diese Seite nutzt aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel Bestellungen oder Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL- bzw. TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von „http://“ auf „https://“ wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.',
      SSL_CONTENT_2:'Wenn die SSL- bzw. TLS-Verschlüsselung aktiviert ist, können die Daten, die Sie an uns übermitteln, nicht von Dritten mitgelesen werden.',
      COLLECTION_WEBSITE:'4. Datenerfassung auf dieser Website',
      COLLECTION_WEBSITE_TITLE:'Anfrage per E-Mail, Telefon oder Telefax',
      COLLECTION_WEBSITE_CONTENT_1:'Wenn Sie uns per E-Mail, Telefon oder Telefax kontaktieren, wird Ihre Anfrage inklusive aller daraus hervorgehenden personenbezogenen Daten (Name, Anfrage) zum Zwecke der Bearbeitung Ihres Anliegens bei uns gespeichert und verarbeitet. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.',
      COLLECTION_WEBSITE_CONTENT_2:'Die Verarbeitung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage mit der Erfüllung eines Vertrags zusammenhängt oder zur Durchführung vorvertraglicher Maßnahmen erforderlich ist. In allen übrigen Fällen beruht die Verarbeitung auf unserem berechtigten Interesse an der effektiven Bearbeitung der an uns gerichteten Anfragen (Art. 6 Abs. 1 lit. f DSGVO) oder auf Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) sofern diese abgefragt wurde; die Einwilligung ist jederzeit widerrufbar.',
      COLLECTION_WEBSITE_CONTENT_3:'Die von Ihnen an uns per Kontaktanfragen übersandten Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen, insbesondere gesetzliche Aufbewahrungsfristen, bleiben unberührt.',
      COLLECTION_WEBSITE_CONTENT_4:'Quelle:',

      HEADER_TITLE: 'Ich bin',
      HEADER_SUBTITLE: 'FRONTEND ENTWICKLERIN',
      HEADER_BUTTON: 'Reden wir',

      SCROLL_ICON:'nach unten',

      ABOUT_ME_TITLE:'Über mich',
      ABOUT_ME_DESCRIPTION:'Ich bin eine Front-End-Entwicklerin mit umfassender Erfahrung in Angular. Mit einem soliden Hintergrund in Ingenieur- und technischen Bereichen bringe ich ein vielseitiges Profil mit, das technologische Expertise und kreative IT-Fähigkeiten vereint. Mein Studium vermittelt mir ein tiefes Verständnis für innovative Technologien und bildet eine robuste Grundlage für meine Rolle als Webentwickler. Versiert in JavaScript bin ich ein kompetenter Webentwickler mit einer starken Basis in IT-Praktiken. Meine Expertise umfasst fortgeschrittene Versionskontrolle mit Git, nahtlose Integration von APIs und eine engagierte Einhaltung der SCRUM-Methodik für effizientes Projektmanagement. Ich verfüge über ein fundiertes Verständnis von HTML und lege großen Wert auf sichere Codierpraktiken, um robuste Weblösungen zu gewährleisten. Darüber hinaus nutze ich Frameworks wie Angular, integriere Bibliotheken wie Bootstrap und verwende Cascading Style Sheets (CSS), um visuell ansprechende und responsive Webdesigns zu erstellen.',
      ABOUT_ME_DESCRIPTION_2:'Meine Fachkenntnisse erstrecken sich auch auf die App-Entwicklung und zeigen ein umfassendes Verständnis moderner Webtechnologien sowie ein Engagement für die Bereitstellung innovativer und benutzerorientierter Lösungen.',
      ABOUT_ME_DESCRIPTION_3:'Mit einem soliden Hintergrund in Ingenieurwissenschaften und technischen Bereichen präsentiere ich ein vielseitiges Profil, das technologische Expertise mit kreativen IT-Fähigkeiten verbindet. Mein Studium hat mir ein umfassendes Verständnis für innovative Technologien und Kommunikationsplattformen vermittelt und bildet eine solide Grundlage für meine Rolle als Webentwickler.',

      MY_SKILLS_TITLE:'Meine Fähigkeiten',
      MY_SKILLS_DESCRIPTION:'Ich habe meine Fähigkeiten in der Frontend-Entwicklung verfeinert, wodurch ich erfolgreich verschiedene konkrete Projekte umsetzen konnte.',
      MY_SKILLS_BUTTON:'Reden wir',

      MY_WORKS_TITLE:'',
      MY_WORKS_DESCRIPTION:'Diese Seite ist ein Beispiel meiner Arbeit – probieren Sie sie gerne aus.',

      JOIN_DESCRIPTION:'Ich habe eine praktische Lösung für das Aufgabenmanagement entwickelt, inspiriert vom Kanban-System, die eine mühelose und intuitive Organisation von Aufgaben mittels eines einfachen Drag-and-Drop-Mechanismus ermöglicht. Benutzer können Aufgaben nahtlos bestimmten Teammitgliedern zuweisen und profitieren gleichzeitig von der Möglichkeit, Aufgaben für eine optimale Organisation zu kategorisieren. Meine Programmierexpertise zeigt sich in der nahtlosen Integration dieser Funktionen, wodurch ein benutzerfreundliches und zugleich robustes Werkzeug für das Aufgabenmanagement entstanden ist.',
      KOCHWELT_DESCRIPTION:'Ein Pokédex ist eine interaktive Webanwendung, die APIs nutzt, um Daten über Pokémon-Arten abzurufen. Entwickelt mit JavaScript, lädt und zeigt sie dynamisch Informationen wie Aussehen, Fähigkeiten und Lebensräume an, wodurch Nutzer verschiedene Pokémon einfach erkunden können.',
      EPL_DESCRIPTION:'Das Spiel "Jump, Run, and Throw" wurde mit einem objektorientierten Ansatz entwickelt und folgt einem sorgfältig ausgearbeiteten Design. In diesem fesselnden Spielerlebnis helfen die Spieler Pepe dabei, Münzen zu sammeln, während sie strategisch Tabasco-Salsa einsammeln, um den Eskapaden der verrückten Henne entgegenzuwirken. Die Umsetzung hebt meine ausgeprägten Programmierfähigkeiten hervor, da ich interaktive Elemente, Charakterverhalten und Power-Up-Dynamiken nahtlos integriere und so eine immersive und mitreißende Spielumgebung schaffe.',

      CONTACT_TITLE:'Kontakt',
      CONTACT_DESCRIPTION:'Haben Sie ein Problem zu lösen?',
      CONTACT_DESCRIPTION_2:'Kontaktieren Sie mich über dieses Formular – ich freue mich darauf, von Ihnen zu hören, Ihre Ideen kennenzulernen und mit meiner Arbeit zu Ihren Projekten beizutragen.',
      CONTACT_DESCRIPTION_3:'Benötigen Sie einen Frontend-Entwickler?',
      CONTACT_DESCRIPTION_4:'Kontaktieren Sie mich!',

      //Form
      NAME_INPUT:'Dein Name',
      EMAIL_INPUT:'Deine Email',
      MASSAGE_INPUT:'Deine Nachricht',
      NAME_REQUIRED:'Du musst einen Namen eingeben',
      EMAIL_REQUIRED:'Du musst eine EMail eingeben',
      MASSAGE_REQUIRED:'Du musst eine Nachricht eingeben',
      PRIVACY_CHECK:'Ich habe die',
      PRIVACY_CHECK_2:'Datenschutzerklärung',
      PRIVACY_CHECK_3:'gelesen und stimme der Verarbeitung meiner Daten wie beschrieben zu.',
      BUTTON_SENDMAIL:'Absenden',
      SENDMAIL_CONTENT:'Deine Nachricht wurde versendet!',

      FOOTER_IMPRINT:'Impressum',

    },
  };

  private currentLanguage: string = 'en'; // Standardsprache

  // Methode zum Setzen der Standardsprache
  setDefaultLanguage(language: string): void {
    this.currentLanguage = language;
    console.log(`Default language set to: ${language}`);
  }

  // Methode zum Wechseln der Sprache
  useLanguage(language: string): void {
    this.currentLanguage = language;
    console.log(`Language switched to: ${language}`);
  }

  // Methode, um eine Übersetzung basierend auf dem Schlüssel abzurufen
  getTranslation(key: string): string {
    return this.translations[this.currentLanguage][key] || key;
  }

}
